#!/bin/sh -e

# init remote repo
# restic -r sftp:user@host:/path init

# backup host definitions
HOST_LOCAL=192.168.1.2
HOST_REMOTE=home-vpn
TARGET=/mnt/space/backups/note
USER=vvk

ping -c1 -W1 $HOST_LOCAL && HOST=home || HOST=$HOST_REMOTE

export RESTIC_REPOSITORY=sftp:$USER@$HOST:$TARGET
export RESTIC_PASSWORD=

exclude_args="--exclude=.cache --exclude=.gqview/thumbnails --exclude=*.vdi --exclude=.config/discord"

ionice -c3 -p$$

restic backup $exclude_args /etc /usr/local /home/vvk
restic unlock

restic forget --prune --keep-daily 5 --keep-weekly 4 --keep-monthly 3 --keep-yearly 2
