#!/bin/sh -e

script_dir="${0%/*}"

config="$script_dir/config"
[ -s "$config" ] && . "$config" || exit 1


if [ x"$ENABLE_HOST_AUTOSELECT" = x"1" ]; then
    ping -c1 -W1 $HOST_LOCAL && HOST=$HOST_LOCAL || HOST=$HOST_REMOTE
fi

if [ x"$REPO_TYPE" = x"sftp" ]; then
    REPO=sftp:$USER@$HOST:$TARGET
elif [ x"$REPO_TYPE" = x"local" ]; then
    REPO=$TARGET
fi

export RESTIC_REPOSITORY=$REPO
export RESTIC_PASSWORD=$RESTIC_PASSWORD


# init remote repo if not exists
if ! restic snapshots >/dev/null; then
    echo "Repo does no exists, initializing"
    restic init
fi

ionice -c3 -p$$

restic backup --exclude-file="$script_dir/excludes.txt" --files-from="$script_dir/includes.txt"
restic unlock
restic forget --prune --keep-daily $KEEP_DAILY --keep-weekly $KEEP_WEEKLY --keep-monthly $KEEP_MONTHLY --keep-yearly $KEEP_YEARLY
